macro(set_local_qt_path QT_LOCAL_PATH)
    get_filename_component(QT_ABSOLUTE_PATH ${QT_LOCAL_PATH} ABSOLUTE)
    message(STATUS "## local QT path = ${QT_ABSOLUTE_PATH}")
    if(NOT EXISTS ${QT_ABSOLUTE_PATH})
        message(FATAL_ERROR "ERROR: QT path not found ${QT_LOCAL_PATH} ${QT_ABSOLUTE_PATH}")
    endif()
    set(CMAKE_PREFIX_PATH ${QT_ABSOLUTE_PATH}/msvc2017/lib/cmake)
    include_directories(${QT_ABSOLUTE_PATH}/msvc2017/include)
endmacro()